version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: auser
      MONGO_INITDB_ROOT_PASSWORD: apassword
  api:
    build: server
    restart: always
  nginx:
    build: client
    restart: always
    ports:
      - 80:8080
