version: '3'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: auser
      MONGO_INITDB_ROOT_PASSWORD: apassword
  api:
    build: server
    container_name: api
    depends_on:
      - "db"
    restart: always
  nginx:
    build: client
    container_name: nginx
    restart: always
    ports:
      - 80:80
